const minimalStyle=document.createElement('link');minimalStyle.rel='stylesheet';minimalStyle.href='minimal.css';document.head.append(minimalStyle);const $=id=>document.getElementById(id);const token=localStorage.getItem('token');const usuario=JSON.parse(localStorage.getItem('usuario')||'null');
if(!token||!usuario||usuario.rol==='admin'){location.href='index.html'}
const ui={saludo:$('saludo'),count:$('count'),catalogo:$('catalogo'),buscar:$('buscar'),filtro:$('filtro'),items:$('items'),total:$('total'),drawer:$('drawer'),shade:$('shade'),modal:$('modal'),mensaje:$('mensaje'),pago:$('pago'),notaPago:$('notaPago')};
ui.saludo.textContent=`Hola, ${usuario.nombre}`;let products=[],cart=JSON.parse(localStorage.getItem('cart')||'[]');
const money=n=>Number(n).toFixed(2);const esc=s=>String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function render(){ui.count.textContent=cart.reduce((sum,item)=>sum+item.qty,0);const query=ui.buscar.value.toLowerCase();const list=products.filter(p=>(!query||`${p.nombre} ${p.descripcion||''}`.toLowerCase().includes(query))&&(!ui.filtro.value||Number(p.stock_actual)>0));ui.catalogo.innerHTML=list.length?list.map(p=>`<article class="product"><img src="${esc(p.imagen_url)||'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80'}" alt="${esc(p.nombre)}"><div class="product-body"><h3>${esc(p.nombre)}</h3><p>${esc(p.descripcion)||'Producto disponible para delivery.'}</p><div class="price">L ${money(p.precio)}</div><div class="stock">${p.stock_actual} disponibles</div><button class="add" data-product="${p.id}" ${Number(p.stock_actual)<1?'disabled':''}>${Number(p.stock_actual)<1?'Agotado':'Agregar al carrito'}</button></div></article>`).join(''):'<div class="empty">No encontramos productos.</div>';ui.catalogo.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>add(Number(b.dataset.product)));ui.items.innerHTML=cart.length?cart.map(x=>`<div class="line"><div><b>${esc(x.nombre)}</b><br>L ${money(x.precio)}</div><div class="qty"><button data-change="${x.id},-1">−</button> ${x.qty} <button data-change="${x.id},1">+</button></div></div>`).join(''):'<div class="empty">Aún no agregas productos.</div>';ui.items.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>{const [id,delta]=b.dataset.change.split(',').map(Number);change(id,delta)});ui.total.textContent=money(cart.reduce((sum,x)=>sum+x.qty*Number(x.precio),0)+(cart.length?50:0));localStorage.setItem('cart',JSON.stringify(cart))}
function add(id){const p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id);if(item&&item.qty>=Number(p.stock_actual))return;item?item.qty++:cart.push({...p,qty:1});render()}function change(id,delta){const item=cart.find(x=>x.id===id);item.qty+=delta;if(item.qty<1)cart=cart.filter(x=>x.id!==id);render()}
async function load(){try{const r=await fetch('/api/productos/productos/publicos');if(!r.ok)throw new Error();products=await r.json();render()}catch{ui.catalogo.innerHTML='<div class="empty">No fue posible cargar el catálogo. Intenta actualizar la página.</div>'}}
const notes={'Efectivo contra entrega':'Paga al recibir tu pedido.','Transferencia bancaria':'El administrador validará tu transferencia antes del envío.','Tarjeta al recibir':'El repartidor llevará un POS para pagar con tarjeta al recibir.'};ui.pago.onchange=()=>ui.notaPago.textContent=notes[ui.pago.value];ui.buscar.oninput=ui.filtro.onchange=render;$('openCart').onclick=()=>{ui.drawer.classList.add('open');ui.shade.classList.add('open')};function close(){ui.drawer.classList.remove('open');ui.shade.classList.remove('open')}$('closeCart').onclick=ui.shade.onclick=close;$('checkout').onclick=()=>{if(cart.length)ui.modal.classList.add('open')};$('closeModal').onclick=()=>ui.modal.classList.remove('open');$('logout').onclick=()=>{localStorage.clear();location.href='index.html'};$('formPedido').onsubmit=async e=>{e.preventDefault();ui.mensaje.textContent='';try{const r=await fetch('/api/ordenes/pedidos',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({items:cart.map(x=>({producto_id:x.id,cantidad:x.qty})),direccion_entrega:$('direccion').value,telefono_entrega:$('telefono').value,metodo_pago:ui.pago.value})});const d=await r.json();if(!r.ok)throw new Error(d.error);cart=[];render();ui.modal.classList.remove('open');close();alert(`Pedido #${d.pedido.id} confirmado.`);load()}catch(err){ui.mensaje.textContent=err.message||'No se pudo confirmar el pedido'}};load();
