server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/auth/ { proxy_pass http://auth:3001/; }
    location /api/productos/ { proxy_pass http://productos:3002/; }
    location /api/inventario/ { proxy_pass http://inventario:3003/; }
    location /api/proveedores/ { proxy_pass http://proveedores:3005/; }
    location /api/clientes/ { proxy_pass http://clientes:3006/; }
    location /api/ordenes/ { proxy_pass http://ordenes:3007/; }
    location /uploads/ { proxy_pass http://productos:3002; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
